name: Feature request
description: Suggest an idea for Unprompted
labels: ["enhancement"]

body:
	- type: checkboxes
		id: due-diligence
		attributes:
			label: Due diligence
			description: Before filing a feature request, please confirm that you have performed your due diligence as described below.
			options:
				- label: I checked for similar requests and couldn't find any.
					required: true
				- label: I read the manual and am at least reasonably sure this idea/feature doesn't already exist.
					required: true
  - type: textarea
    id: feature
    attributes:
      label: Your idea
      description: Tell us about your feature in a very clear and simple way, and what problem(s) it would solve. Thank you!
    validations:
      required: true